name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libjpeg-dev zlib1g-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p static/uploads
        mkdir -p static/processed

    - name: Run Flask application
      run: |
        nohup python app.py > flask.log 2>&1 &
        sleep 5
        curl http://localhost:5000

  # deploy-to-heroku:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: akhileshns/heroku-deploy@v3.12.12
  #     with:
  #       heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #       heroku_app_name: "your-app-name"
  #       heroku_email: "your-email@example.com"