name: Flask Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libjpeg-dev zlib1g-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Create test config
      run: |
        mkdir -p static/uploads
        mkdir -p static/processed
        cat << EOF > config.py
        RECAPTCHA_SITE_KEY = 'test_key'
        RECAPTCHA_SECRET_KEY = 'test_key'
        UPLOAD_FOLDER = 'static/uploads'
        PROCESSED_FOLDER = 'static/processed'
        ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
        SECRET_KEY = 'test_secret_key_123'
        TESTING = True
        EOF
    
    - name: Run tests with pytest
      env:
        FLASK_ENV: testing
      run: |
        python -m pytest tests/ -v --cov=app --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests