name: Flask Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create test config
      run: |
        mkdir -p static/uploads
        mkdir -p static/processed
        echo "RECAPTCHA_SITE_KEY = 'test_key'" > config.py
        echo "RECAPTCHA_SECRET_KEY = 'test_key'" >> config.py
        echo "UPLOAD_FOLDER = 'static/uploads'" >> config.py
        echo "PROCESSED_FOLDER = 'static/processed'" >> config.py
        echo "ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}" >> config.py
        echo "SECRET_KEY = 'test_secret_key'" >> config.py
    
    - name: Run tests with pytest
      run: |
        python -m pytest tests/ -v --cov=app --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests